on:
  push:
    branches:
      - main
jobs:
  deploy-dev:
    environment: dev
    concurrency:
      group: deploy-dev
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
        -  name: Fake deploy step
           run: echo "Deploying to dev..."
  deploy-test:
    needs: deploy-dev
    environment: test
    concurrency:
      group: deploy-test
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
        -  name: Fake deploy step
           run: echo "Deploying to test..."
  deploy-prod:
    needs: deploy-test
    concurrency:
      group: deploy-prod
      cancel-in-progress: true
    environment: prod
    runs-on: ubuntu-latest
    steps:
        -  name: Fake deploy step
           run: echo "Deploying to production..."