on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-dev:
    environment: dev
    runs-on: ubuntu-latest
    steps:
        -  name: Fake deploy step
           run: echo "Deploying to dev..."
  deploy-test:
    needs: deploy-dev
    environment: test
    runs-on: ubuntu-latest
    steps:
        -  name: Fake deploy step
           run: echo "Deploying to test..."
  deploy-prod:
    needs: deploy-test
    environment: prod
    runs-on: ubuntu-latest
    steps:
        -  name: Fake deploy step
           run: echo "Deploying to production..."