name: Build & Deploy

on:
  push:
    branches:
      - main
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ matrix.environment }}
    strategy:
      max-parallel: 1 # Ensures jobs run one by one
      fail-fast: true # Cancels remaining jobs if one fails
      matrix:
        environment: [dev, test, prod] # Define your environments here
    steps:
      - name: Deploy to ${{ matrix.environment }}
        run: |
          echo "Deploying to ${{ matrix.environment }} environment..."